export enum SalesCompany {
  Magnum = "Magnum",
  Azul = "Azul",
  TM = "TM",
  AssetFolio = "Asset Folio",
  OneEden = "One Eden",
  Aedas = "Aedas",
  BromleyEstate = "Bromley Estate",
  MXM = "MXM",
  PrimeInvest = "Prime Invest",
  ON3 = "ON3",
  GILMAR = "GILMAR",
  RossoInmobiliaria = "Rosso Inmobiliaria",
  Nvoga = "Nvoga",
  TaylorWimpey = "Taylor Wimpey",
  TuscanyGroup = "Tuscany Group",
  RHPriveEstates = "RH Prive Estates",
  DreamExclusives = "Dream Exclusives",
  HigueronRealEstate = "Higueron Real Estate",
  Insur = "Insur",
  BySales = "By Sales",
  InvestHome = "Invest Home",
  RealDeLaQuinta = "Real De La Quinta",
  CapreHomes = "Capre Homes",
  UrbinCasa = "Urbin Casa",
  Turnkey = "Turnkey",
  Others = "Others",
}
