export enum SalesCompany {
  Magnum = "Magnum",
  Azul = "Azul",
  TM = "TM",
  AssetFolio = "AssetFolio",
  OneEden = "OneEden",
  Aedas = "Aedas",
  BromleyEstate = "BromleyEstate",
  MXM = "MXM",
  PrimeInvest = "PrimeInvest",
  ON3 = "ON3",
  GILMAR = "GILMAR",
  RossoInmobiliaria = "RossoInmobiliaria",
  Nvoga = "Nvoga",
  TaylorWimpey = "TaylorWimpey",
  TuscanyGroup = "TuscanyGroup",
  RHPriveEstates = "RHPriveEstates",
  DreamExclusives = "DreamExclusives",
  HigueronRealEstate = "HigueronRealEstate",
  Insur = "Insur",
  BySales = "BySales",
  InvestHome = "InvestHome",
  RealDeLaQuinta = "RealDeLaQuinta",
  CapreHomes = "CapreHomes",
  UrbinCasa = "UrbinCasa",
  Turnkey = "Turnkey",
  Others = "Others",
}
